### ISSUE TITLE
Getting error ERROR - Exception while exporting Span batch.

### ISSUE THREAD

**Issue by epsilonion-liam** [exorde-labs/youtube00e1f862e5eff#1]
A little help with this error with the youtube scraper, it just scrapes the videos and shows this error following scraping.

```
2024-07-07 10:48:02,435 - ERROR - Exception while exporting Span batch.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/opentelemetry/sdk/trace/export/__init__.py", line 367, in _export_batch
    self.span_exporter.export(self.spans_list[:idx])  # type: ignore
  File "/usr/local/lib/python3.10/site-packages/opentelemetry/exporter/jaeger/thrift/__init__.py", line 225, in export
    self._agent_client.emit(batch)
  File "/usr/local/lib/python3.10/site-packages/opentelemetry/exporter/jaeger/thrift/send.py", line 95, in emit
    udp_socket.sendto(buff, self.address)
socket.gaierror: [Errno -2] Name or service not known
2024-07-07 10:48:02,541 - INFO - [Youtube] - Scraping latest comments posted less than 2000 seconds ago, on youtube videos related to keyword: kraken.
2024-07-07 10:48:02,541 - INFO - [Youtube] Adding search filter to URL:  last hour videos
2024-07-07 10:48:02,541 - INFO - [Youtube] Looking at video URL: https://www.youtube.com/results?search_query=kraken&sp=EgQIARAB
2024-07-07 10:48:05,263 - INFO - [Youtube] Parsing search page: raw contents found...
2024-07-07 10:48:05,263 - INFO - [Youtube] urls or titles is empty, skipping...
2024-07-07 10:48:05,265 - INFO - Stopped Iteration
2024-07-07 10:48:06,266 - INFO - scraping loop
2024-07-07 10:48:06,267 - INFO - module name is youtube00e1f862e5eff
2024-07-07 10:48:06,267 - DEBUG -  random_number: 23 ; algorithm_choose_cursor: 35
2024-07-07 10:48:06,268 - INFO - intercompatible_languages: ['en', 'zh', 'ja', 'ar', 'hi', 'ko', 'th', 'vi', 'ru', 'tr', 'es', 'fa']
2024-07-07 10:48:06,268 - INFO - choosed new keyword 'Лимпо' (alg: new)
2024-07-07 10:48:06,269 - INFO - Parameters are : {'url_parameters': {'keyword': 'Лимпо'}, 'keyword': 'Лимпо', 'max_oldness_seconds': 2000, 'maximum_items_to_collect': 25, 'min_post_length': 5, 'max_total_comments_to_check': 200, 'probability_to_select_default_kws': 0.42}
2024-07-07 10:48:07,270 - INFO - [Youtube] - Scraping latest comments posted less than 2000 seconds ago, on youtube videos related to keyword: 機械学習.
2024-07-07 10:48:07,271 - INFO - [Youtube] Adding search filter to URL:  relevant videos
2024-07-07 10:48:07,271 - INFO - [Youtube] Looking at video URL: https://www.youtube.com/results?search_query=機械学習&sp=CAASAhAB
2024-07-07 10:48:07,435 - ERROR - Exception while exporting Span batch.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/opentelemetry/sdk/trace/export/__init__.py", line 367, in _export_batch
    self.span_exporter.export(self.spans_list[:idx])  # type: ignore
  File "/usr/local/lib/python3.10/site-packages/opentelemetry/exporter/jaeger/thrift/__init__.py", line 225, in export
    self._agent_client.emit(batch)
  File "/usr/local/lib/python3.10/site-packages/opentelemetry/exporter/jaeger/thrift/send.py", line 95, in emit
    udp_socket.sendto(buff, self.address)
socket.gaierror: [Errno -2] Name or service not known
```

If you could let me know what the error is regarding as I would like to educate myself.

**Comment by epsilonion-liam** [comment]
delete please remade issue
